// ============ 状态图标与名称映射（共享模块：React版与单文件版复用） ============
export const STATUS_IMG_FIX: Record<string, string> = {
  angry: 'anger',            // 素材库文件名为 anger.png
  metallicizeE: 'metallicize', // 敌人金属化复用 metallicize 图标
  asleep: '../intent/sleep',   // 沉睡复用意图 Zzz 图标
  wraithFormS: 'intangible',
  phantasmal: 'phantasmal',
  blasphemyD: 'divinity',
  vaultS: 'divinity',
  alphaS: 'devotion',
  betaActive: 'devotion',
  omegaActive: 'wrath',
  foresight: 'foresight',
  creativeAI: 'creativeAI',
  machineLearning: 'foresight',
  capacitor: 'focus',
  echoForm: 'echo',
  amplifyS: 'amplify',
  loopS: 'loop',
  staticDischargeS: 'staticDischarge',
  stormS: 'storm',
  accuracy: 'accuracy',
  afterImage: 'afterImage',
  aThousandCuts: 'aThousandCuts',
  caltropsS: 'caltrops',
  envenomS: 'envenom',
  equilibriumS: 'equilibrium',
  mentalFortressS: 'mentalFortress',
  likeWaterS: 'likeWater',
  nirvanaS: 'nirvana',
  devotionS: 'devotion',
  brillianceS: 'brilliance',
  corpseExplosionS: 'corpseExplosion',
  beatOfDeath: 'beatOfDeath',
  entangled: 'entangled',
  noxiousFumesS: 'noxiousFumes',
  rebirthS: 'rebirth',
  phasingS: 'phasing',
  theBombS: 'theBomb',
  masterRealityS: 'masterReality',
  establishmentS: 'establishment',
  heatsinksS: 'heatsinks',
  rushdownS: 'likeWater',
  electroS: 'electro',
}

export const STATUS_IMG_MISSING = new Set(['divotion_placeholder', 'shackle_placeholder'])

// base: React版传 '/assets'；单文件版传 A()（素材键函数返回 base64 data URI 前缀时由调用方处理）
export function statusImgPath(id: string, base: string, resolve?: (key: string) => string): string {
  const fix = STATUS_IMG_FIX[id]
  const key = fix
    ? (fix.startsWith('../') ? fix.slice(3) : 'status/' + fix) + '.png'
    : 'status/' + id + '.png'
  if (resolve) return resolve(key)
  return base + '/' + key
}

export const STATUS_INFO: Record<string, { name: string; desc: string; buff?: boolean }> = {
  strength: { name: '力量', desc: '每点力量使攻击伤害 +1。', buff: true },
  dexterity: { name: '敏捷', desc: '每点敏捷使获得的格挡 +1。', buff: true },
  vulnerable: { name: '易伤', desc: '受到的攻击伤害 ×1.5。每回合结束 -1。' },
  weak: { name: '虚弱', desc: '造成的攻击伤害 ×0.75。每回合结束 -1。' },
  frail: { name: '脆弱', desc: '获得的格挡 ×0.75。每回合结束 -1。' },
  artifact: { name: '反制', desc: '下 N 次受到的负面效果被无效化。', buff: true },
  thorns: { name: '尖刺', desc: '被攻击时对攻击者造成 N 点伤害。', buff: true },
  metallicize: { name: '金属化', desc: '回合结束时获得 N 点格挡。', buff: true },
  regen: { name: '回复', desc: '回合开始时回复 N 点生命，然后 -1。', buff: true },
  ritual: { name: '仪式', desc: '回合开始时获得 N 点力量。', buff: true },
  demonForm: { name: '恶魔形态', desc: '回合开始时获得 N 点力量。', buff: true },
  barricade: { name: '壁垒', desc: '格挡不再在回合开始时消失。', buff: true },
  brutality: { name: '残暴', desc: '回合开始时失去 1 点生命并抽 1 张牌。', buff: true },
  corruption: { name: '堕落', desc: '技能牌费用为 0，打出后消耗。', buff: true },
  combust: { name: '燃烧', desc: '回合结束时失去 1 点生命，对所有敌人造成 N 点伤害。', buff: true },
  darkEmbrace: { name: '暗黑拥抱', desc: '每当有牌被消耗时抽 1 张牌。', buff: true },
  evolve: { name: '进化', desc: '抽到状态牌时额外抽 N 张牌。', buff: true },
  feelNoPain: { name: '无痛', desc: '每当有牌被消耗时获得 N 点格挡。', buff: true },
  fireBreathing: { name: '火焰吐息', desc: '抽到状态/诅咒牌时对所有敌人造成 N 点伤害。', buff: true },
  rupture: { name: '破裂', desc: '因打牌失去生命时获得 N 点力量。', buff: true },
  juggernaut: { name: '主宰', desc: '获得格挡时对随机敌人造成 N 点伤害。', buff: true },
  berserk: { name: '狂暴', desc: '回合开始时获得 1 点能量。', buff: true },
  rage: { name: '狂怒', desc: '本回合每打出一张攻击牌获得 N 点格挡。', buff: true },
  doubleTap: { name: '连击', desc: '接下来 N 张攻击牌被打出两次。', buff: true },
  noDraw: { name: '无法抽牌', desc: '本回合无法再抽牌。' },
  angry: { name: '激怒', desc: '你每打出一张技能牌，获得 N 点力量。' },
  asleep: { name: '沉睡', desc: '沉睡中，受到攻击会立即醒来。' },
  curlUp: { name: '蜷缩', desc: '首次受到攻击伤害时获得 N 点格挡。' },
  metallicizeE: { name: '金属化', desc: '回合结束时获得 N 点格挡。' },
  flameBarrier: { name: '火焰屏障', desc: '本回合被攻击时对攻击者造成 N 点伤害。', buff: true },
  modeShift: { name: '模式切换', desc: '守卫者的防御模式，格挡攒满后切换攻击模式。' },
  // ---- 新角色/新怪物状态 ----
  poison: { name: '中毒', desc: '回合开始时受到等同于层数的伤害，然后层数 -1。' },
  focus: { name: '集中', desc: '增强充能球的被动与唤起效果。', buff: true },
  intangible: { name: '虚无形体', desc: '受到的任何伤害变为 1 点。', buff: true },
  lockOn: { name: '锁定', desc: '受到的闪电伤害提高 50%。' },
  mark: { name: '印记', desc: '每当你施加印记，敌人失去等同其印记层数的生命值。' },
  mantra: { name: '真言', desc: '累积 10 点真言时进入神格姿态。', buff: true },
  constricted: { name: '束缚', desc: '回合结束时受到等同层数的伤害。' },
  hex: { name: '咒术', desc: '每当你打出一张非攻击牌，受到 3 点伤害，然后层数 -1。' },
  flying: { name: '飞行', desc: '受到的攻击伤害降低 40%。', buff: true },
  time: { name: '时间', desc: '时间吞噬者：你每打出一张牌层数 +1，达到 8 层时获得力量并重置。' },
  beatOfDeath: { name: '死亡节拍', desc: '腐朽之心：你每打出一张牌，受到 2 点伤害。' },
  accuracy: { name: '精准', desc: '小刀造成的伤害提高 N 点。', buff: true },
  afterImage: { name: '残像', desc: '每当你打出一张牌，获得 N 点格挡。', buff: true },
  aThousandCuts: { name: '千刀万剐', desc: '每当你打出一张牌，对所有敌人造成 N 点伤害。', buff: true },
  caltropsS: { name: '蒺藜', desc: '每当你被攻击时，对攻击者造成 N 点伤害。', buff: true },
  envenomS: { name: '淬毒', desc: '攻击造成的未被格挡伤害施加 N 层中毒。', buff: true },
  echoForm: { name: '回声形态', desc: '每回合你打出的第一张牌将被打出两次。', buff: true },
  amplifyS: { name: '扩增', desc: '本回合你打出的下 N 张能力牌将被打出两次。', buff: true },
  loopS: { name: '循环', desc: '回合开始时，触发最右侧充能球的被动效果 N 次。', buff: true },
  staticDischargeS: { name: '静电释放', desc: '每当你受到攻击伤害，引导 N 个闪电球。', buff: true },
  stormS: { name: '风暴', desc: '每当你打出一张能力牌，引导 N 个闪电球。', buff: true },
  equilibriumS: { name: '平衡', desc: '本回合保留手牌。', buff: true },
  mentalFortressS: { name: '心灵壁垒', desc: '每当你切换姿态，获得 N 点格挡。', buff: true },
  likeWaterS: { name: '静如水', desc: '回合结束时若处于静相，获得 N 点格挡。', buff: true },
  nirvanaS: { name: '涅槃', desc: '每当你预见一张牌，获得 N 点格挡。', buff: true },
  devotionS: { name: '奉献', desc: '回合开始时获得 N 点真言。', buff: true },
  brillianceS: { name: '光辉', desc: '每当你获得真言，对随机敌人造成 N 点伤害。', buff: true },
  alphaS: { name: '阿尔法', desc: '回合开始时将一张贝塔加入手牌。', buff: true },
  betaActive: { name: '贝塔', desc: '回合开始时将一张欧米茄加入手牌。', buff: true },
  omegaActive: { name: '欧米茄', desc: '回合结束时对所有敌人造成 50 点伤害。', buff: true },
  foresight: { name: '先见之明', desc: '回合结束时预见 N 张牌。', buff: true },
  creativeAI: { name: '创造AI', desc: '回合开始时将一张随机能力牌加入手牌。', buff: true },
  machineLearning: { name: '机器学习', desc: '回合开始时多抽 N 张牌。', buff: true },
  capacitor: { name: '电容器', desc: '充能球上限提高 N 点。', buff: true },
  burstS: { name: '连发', desc: '本回合你打出的下 N 张技能牌将被打出两次。', buff: true },
  phantasmal: { name: '幻影杀手', desc: '下一张攻击牌造成的伤害翻倍。', buff: true },
  blasphemyD: { name: '亵渎', desc: '下回合开始时，你将死亡。' },
  vaultS: { name: '穹顶', desc: '跳过敌人的回合。', buff: true },
  rebirth: { name: '重生', desc: '首次死亡时复活至半血并获得力量。', buff: true },
  entangled: { name: '纠缠', desc: '本回合无法打出攻击牌。' },
  electro: { name: '电涌', desc: '闪电球命中所有敌人。', buff: true },
  theBomb: { name: '炸弹', desc: '回合结束时对所有敌人造成 N 点伤害。', buff: true },
  corpseExplosionS: { name: '尸体爆炸', desc: '该敌人死亡时，对所有敌人造成其最大生命值的伤害。', buff: true },
  wraithFormS: { name: '幽魂形态', desc: '回合结束时失去 1 点敏捷。', buff: true },
}
